name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Debug Test Discovery
      run: dotnet test TownSquareAPI.Tests/TownSquareAPI.Tests.csproj --list-tests

    - name: Run Tests
      run: dotnet test TownSquareAPI.Tests/TownSquareAPI.Tests.csproj --no-build --verbosity normal
